#! /usr/bin/env python
# encoding: utf-8

from waflib import Build
from subprocess import call

dirs = [
       # "posix"
    ]

def options(ctx):
    pass

def configure(ctx):
    for d in dirs:
        ctx.recurse(d)
    pass

def build(ctx):
    for d in dirs:
        ctx.recurse(d)
    pass
