.\" Manpage for feign.
.\" Use https://github.com/jakobluettgau/feign to correct errors or typos.
.TH man 1 "01 May 2014" "1.0" "feign man page"
.SH NAME
feign \- flexible event imitation engine
.SH SYNOPSIS
fein [--plugin PATH-TO-PLUGIN] [TRACEFILE]
.SH DESCRIPTION
feign can replay trace files to mimic the characteristics of an application. 
.SH OPTIONS
--plugin	add a plugin path that feign should load
.SH SEE ALSO
strace(1), ltrace(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Jakob Luettgau (jakob@whatz.eu)
